version: "3"

services:
  redis_main:
    image: redis:5
    volumes:
      - ./redis_main_data/:/data/
    restart: unless-stopped

  redis_cache:
    image: redis:5
    volumes:
      - ./redis_cache_data/:/data/
    restart: unless-stopped

  # minio:
  #   image: minio/minio
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   volumes:
  #     - minio-data:/data
  #   environment:
  #     MINIO_ROOT_USER: ${MINIO_USERNAME}
  #     MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
  #   command: server --console-address ":9001" /data

  # createbuckets:
  #   image: minio/mc
  #   depends_on:
  #     - minio
  #   entrypoint: >
  #     /bin/sh -c "
  #     /usr/bin/mc config host add myminio http://minio:9000 ${MINIO_USERNAME} ${MINIO_PASSWORD};
  #     /usr/bin/mc rm -r --force myminio/${MINIO_BUCKETNAME};
  #     /usr/bin/mc mb myminio/${MINIO_BUCKETNAME};
  #     /usr/bin/mc anonymous set public myminio/${MINIO_BUCKETNAME};
  #     exit 0;
  #     "

  fm-cache:
    image: redis:7
    volumes:
      - ./fm_redis_data/:/data/
    restart: unless-stopped

  form-manager:
    image: form-manager
    build: packages/form-manager
    depends_on:
      - fm-cache
      # - minio
      # - createbuckets
    ports:
      - 3006:3006
    environment:
      MINIO_USERNAME: ${MINIO_USERNAME}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_PORT: ${MINIO_PORT}
      MINIO_URL: ${MINIO_URL}
      MINIO_PASSWORD: ${MINIO_PASSWORD}
      MINIO_BUCKETNAME: ${MINIO_BUCKETNAME}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      FORM_MANAGER_URL: ${FORM_MANAGER_URL}
      MINIO_USE_SSL: ${MINIO_USE_SSL}
      GCP_BUCKET_NAME: ${GCP_BUCKET_NAME}
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}

networks:
  db_net:
    driver: bridge
  search_net:
    driver: bridge
  default:

volumes:
  db_data:
  search_data:
  minio-data:
  fa-config:
  minio_storage: {}
